version: "3.7"

services:
  portgres:
    image: postgres
    container_name: postgres-container
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=base
    volumes:
     - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-volume:
    driver: local
